name: Jira Transition Times

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Rodar toda segunda-feira às 00:00 UTC

jobs:
  get_jira_times:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Get Jira transition times
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
        run: |
          node get-jira-transitions.js
